name: AWS S3 List Buckets

on:
  push:
    branches:
      - main

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: AWS CLI  creds
        run: |
          aws configure set aws_access_key_id AKIAY5IBI5MKMSOZOFSA
          aws configure set aws_secret_access_key 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
          aws configure set default.region "eu-north-1"
          aws s3 ls
