name: AWS S3 List Buckets

on:
  push:
    branches:
      - main

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          echo "aws-azure-gcp"

      
      
