name: AWS S3 List Buckets

on:
  push:
    branches:
      - main

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key eHN0mvSZHNBTMNNIEEqugKNR00hfHOzWA3QDTyVQ
          aws configure set default.region "eu-north-1"

      - name: List S3 buckets
        run: |
          aws s3 ls
