name: AWS S3 List Buckets

on:
  push:
    branches:
      - main

jobs:
  list-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: AWS CLI  creds
        env:
          access_key: ${{ aws_access_key_id }}
        run: |
          aws configure set aws_access_key_id $access_key
          aws configure set aws_secret_access_key XVKCPvjZEuxsPqGKGYT2RfNINr2Vr6tZSN7yTu79
          aws configure set default.region "eu-north-1"
          aws s3 ls
